/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarCredenciaisRouteImport } from './routes/trocar-credenciais'
import { Route as SemAcessoRouteImport } from './routes/sem-acesso'
import { Route as RegistrosRouteImport } from './routes/registros'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistrosIdRouteImport } from './routes/registros.$id'
import { Route as RegistrosIdEditRouteImport } from './routes/registros.$id.edit'

const TrocarCredenciaisRoute = TrocarCredenciaisRouteImport.update({
  id: '/trocar-credenciais',
  path: '/trocar-credenciais',
  getParentRoute: () => rootRouteImport,
} as any)
const SemAcessoRoute = SemAcessoRouteImport.update({
  id: '/sem-acesso',
  path: '/sem-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrosRoute = RegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosRoute = MembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrosIdRoute = RegistrosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RegistrosRoute,
} as any)
const RegistrosIdEditRoute = RegistrosIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RegistrosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/membros': typeof MembrosRoute
  '/perfil': typeof PerfilRoute
  '/registros': typeof RegistrosRouteWithChildren
  '/sem-acesso': typeof SemAcessoRoute
  '/trocar-credenciais': typeof TrocarCredenciaisRoute
  '/registros/$id': typeof RegistrosIdRouteWithChildren
  '/registros/$id/edit': typeof RegistrosIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/membros': typeof MembrosRoute
  '/perfil': typeof PerfilRoute
  '/registros': typeof RegistrosRouteWithChildren
  '/sem-acesso': typeof SemAcessoRoute
  '/trocar-credenciais': typeof TrocarCredenciaisRoute
  '/registros/$id': typeof RegistrosIdRouteWithChildren
  '/registros/$id/edit': typeof RegistrosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/membros': typeof MembrosRoute
  '/perfil': typeof PerfilRoute
  '/registros': typeof RegistrosRouteWithChildren
  '/sem-acesso': typeof SemAcessoRoute
  '/trocar-credenciais': typeof TrocarCredenciaisRoute
  '/registros/$id': typeof RegistrosIdRouteWithChildren
  '/registros/$id/edit': typeof RegistrosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/membros'
    | '/perfil'
    | '/registros'
    | '/sem-acesso'
    | '/trocar-credenciais'
    | '/registros/$id'
    | '/registros/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/membros'
    | '/perfil'
    | '/registros'
    | '/sem-acesso'
    | '/trocar-credenciais'
    | '/registros/$id'
    | '/registros/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/membros'
    | '/perfil'
    | '/registros'
    | '/sem-acesso'
    | '/trocar-credenciais'
    | '/registros/$id'
    | '/registros/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MembrosRoute: typeof MembrosRoute
  PerfilRoute: typeof PerfilRoute
  RegistrosRoute: typeof RegistrosRouteWithChildren
  SemAcessoRoute: typeof SemAcessoRoute
  TrocarCredenciaisRoute: typeof TrocarCredenciaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-credenciais': {
      id: '/trocar-credenciais'
      path: '/trocar-credenciais'
      fullPath: '/trocar-credenciais'
      preLoaderRoute: typeof TrocarCredenciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sem-acesso': {
      id: '/sem-acesso'
      path: '/sem-acesso'
      fullPath: '/sem-acesso'
      preLoaderRoute: typeof SemAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registros': {
      id: '/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof RegistrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros': {
      id: '/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof MembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registros/$id': {
      id: '/registros/$id'
      path: '/$id'
      fullPath: '/registros/$id'
      preLoaderRoute: typeof RegistrosIdRouteImport
      parentRoute: typeof RegistrosRoute
    }
    '/registros/$id/edit': {
      id: '/registros/$id/edit'
      path: '/edit'
      fullPath: '/registros/$id/edit'
      preLoaderRoute: typeof RegistrosIdEditRouteImport
      parentRoute: typeof RegistrosIdRoute
    }
  }
}

interface RegistrosIdRouteChildren {
  RegistrosIdEditRoute: typeof RegistrosIdEditRoute
}

const RegistrosIdRouteChildren: RegistrosIdRouteChildren = {
  RegistrosIdEditRoute: RegistrosIdEditRoute,
}

const RegistrosIdRouteWithChildren = RegistrosIdRoute._addFileChildren(
  RegistrosIdRouteChildren,
)

interface RegistrosRouteChildren {
  RegistrosIdRoute: typeof RegistrosIdRouteWithChildren
}

const RegistrosRouteChildren: RegistrosRouteChildren = {
  RegistrosIdRoute: RegistrosIdRouteWithChildren,
}

const RegistrosRouteWithChildren = RegistrosRoute._addFileChildren(
  RegistrosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MembrosRoute: MembrosRoute,
  PerfilRoute: PerfilRoute,
  RegistrosRoute: RegistrosRouteWithChildren,
  SemAcessoRoute: SemAcessoRoute,
  TrocarCredenciaisRoute: TrocarCredenciaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
