// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    throw new Error(
      "Missing Supabase server environment variables. Ensure SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set.",
    );
  }

  if (!SUPABASE_SERVICE_ROLE_KEY.startsWith("eyJ")) {
    throw new Error(
      'A chave SUPABASE_SERVICE_ROLE_KEY no arquivo .env é inválida. Ela deve ser um JWT (começando com eyJ...). Vá no painel do Supabase > Project Settings > API > Project API keys e copie a chave "service_role" (secret).',
    );
  }

  const SUPABASE_PUBLISHABLE_KEY =
    process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  if (SUPABASE_SERVICE_ROLE_KEY === SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "ALERTA: Você colou a mesma chave em SUPABASE_SERVICE_ROLE_KEY e SUPABASE_PUBLISHABLE_KEY! A service_role key é diferente e fica logo abaixo da chave anon/public no painel do Supabase. A chave que você colocou tem permissões de usuário anônimo (não ignora o RLS), por isso você está sem acesso.",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
